### ISSUE TITLE
if the two new transactions at every level can be refreshed

### ISSUE THREAD

**Issue by Cindystick** [Minecraft-LightLand/TradeRefresh#1]
In fact, if it can be changed to, every time the villagers upgrade and unlock two transactions, the players can refresh the two new transactions at this level until the transaction is bound.

That is, transactions at every level can be refreshed, not just the initial ones.

**Comment by lcy0x1** [comment]
I just want to make a shortcut to vanilla break and place work station. What you mentioned is not achievable in vanilla.

I will still consider it but I will make it default off

**Comment by Cindystick** [comment]
If you're willing to consider it, it's really nice, what a pleasure.

**Comment by lcy0x1** [comment]
I think I implemented it. Please join discord if you want to test it

**Comment by lcy0x1** [comment]
implemented
